"""add_extensions

Revision ID: 4c21e357351c
Revises:
Create Date: 2024-08-15 13:25:54.333715

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "4c21e357351c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add btree_gist extension (not autogenerated)
    op.execute(text("CREATE EXTENSION IF NOT EXISTS btree_gist;"))


def downgrade() -> None:
    # drop btree_gist extension (not autogenerated)
    op.execute(text("DROP EXTENSION IF EXISTS btree_gist;"))
