"""item-image many-to-many relationship

Revision ID: 4f2e8642cffe
Revises: d5f03f0ce371
Create Date: 2025-02-16 19:22:16.649299
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f2e8642cffe"
down_revision: Union[str, None] = "d5f03f0ce371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_image_association",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("image_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_name"], ["item_image.name"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "image_name"),
    )
    op.drop_constraint("item_image_item_id_fkey", "item_image", type_="foreignkey")
    op.drop_column("item_image", "item_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_image",
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "item_image_item_id_fkey",
        "item_image",
        "item",
        ["item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("item_image_association")
    # ### end Alembic commands ###
