"""add category tables

Revision ID: 5b5c5a10390e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-03 21:21:53.789982
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b5c5a10390e"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_slug", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_slug"], ["category.slug"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_index(
        op.f("ix_category_parent_slug"), "category", ["parent_slug"], unique=False
    )
    op.create_index(op.f("ix_category_slug"), "category", ["slug"], unique=False)
    op.create_table(
        "item_category_association",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("category_slug", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_slug"], ["category.slug"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("item_id", "category_slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_category_association")
    op.drop_index(op.f("ix_category_slug"), table_name="category")
    op.drop_index(op.f("ix_category_parent_slug"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
