from .cmdline import WonderwordsCommandLine as WonderwordsCommandLine
from .random_sentence import RandomSentence as RandomSentence
from .random_word import NoWordsToChoseFrom as NoWordsToChoseFrom
from .random_word import RandomWord as RandomWord

def main() -> None: ...
def get_mode(arguments): ...
def handle_mode(mode, arguments) -> None: ...
