from _typeshed import Incomplete

from . import __version__ as __version__

console: Incomplete
AVAILABLE_COMMANDS: str

class WonderwordsCommandLine:
    def print_title(self) -> None: ...
    def print_commands(self) -> None: ...
    def version(self) -> None: ...
    def intro(self) -> None: ...
    def word(self, word) -> None: ...
    def words(self, words, delimiter) -> None: ...
    def sentence(self, sent) -> None: ...
    def no_word(self) -> None: ...
    def no_words(self) -> None: ...
