services:

  # database
  db:
    image: postgres
    ports: [5432]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # use in-memory db data for speed
    tmpfs:
      - /var/lib/postgresql/data

  # images storage service
  images:
    image: "hauxir/imgpush:latest"
    ports: [5000]
