services:

  # backend api server
  api:
    environment:
      API_PREFIX: ${API_PREFIX}
      API_PORT: 8080
      API_TEST_MODE: true
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: 89f29e10db6bf143f91496ed4cd1952f
    build:
      context: api/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: api/
        target: /usr/src/api/
    depends_on:
      - db

  # database
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    # use in-memory db data for speed
    tmpfs:
      - /var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
