# TODO add healthchecks
# TODO add logging system
# TODO add metrics

services:
  # images storage service
  images:
    image: hauxir/imgpush:latest
    environment:
      MAX_UPLOADS_PER_MINUTE: 1000
      MAX_UPLOADS_PER_HOUR: 5000
      MAX_UPLOADS_PER_DAY: 50000
      # NUDE_FILTER_MAX_THRESHOLD: 0.60
    volumes:
      - type: bind
        source: /var/lib/imgpush/data
        target: /images
    ports:
      - 127.0.0.1:5000:5000
  # backend api server
  babytroc-api:
    image: "ghcr.io/vianneyrousset/babytroc-api:latest"
    container_name: "babytroc-api"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: "babytroc"
      POSTGRES_USER: "babytroc"
      IMGPUSH_HOST: "localhost"
      IMGPUSH_PORT: 5000
      API_PREFIX: "/api"
      JWT_ALGORITHM: "HS256"
      JWT_REFRESH_TOKEN_DURATION_DAYS: "7"
      JWT_ACCESS_TOKEN_DURATION_MINUTES: "15"
    depends_on:
      - images
    ports:
      - 127.0.0.1:8080:8080
    network_mode: "host"
  # frontend server
  babytroc-gui:
    image: "ghcr.io/vianneyrousset/babytroc-gui:latest"
    container_name: "babytroc-gui"
    depends_on:
      - babytroc-api
    ports:
      - 127.0.0.1:3000:3000
