# TODO add healthchecks
# TODO add logging system
# TODO add metrics

services:
  # images storage service
  images:
    image: hauxir/imgpush:latest
    environment:
      MAX_UPLOADS_PER_MINUTE: 1000
      MAX_UPLOADS_PER_HOUR: 5000
      MAX_UPLOADS_PER_DAY: 50000
      # NUDE_FILTER_MAX_THRESHOLD: 0.60
    volumes:
      - type: bind
        source: /var/lib/imgpush/data
        target: /images
    ports:
      - 127.0.0.1:5000:5000
  # backend api server
  babytroc-api:
    image: "ghcr.io/vianneyrousset/babytroc-api:latest"
    container_name: "babytroc-api"
    environment:
      # options
      HOST_NAME: "${HOST_NAME:?Missing HOST_NAME}"
      APP_NAME: "${APP_NAME:-Babytroc}"
      API_PREFIX: "${APP_NAME:-/api}"
      ACCOUNT_PASSWORD_RESET_AUTHORIZATION_DURATION_MINUTES: "${ACCOUNT_PASSWORD_RESET_AUTHORIZATION_DURATION_MINUTES:-20}"
      # database
      POSTGRES_HOST: "${POSTGRES_HOST:-localhost}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE:-babytroc}"
      POSTGRES_USER: "${POSTGRES_USER:-babytroc}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?Missing POSTGRES_PASSWORD}"
      # jwt
      JWT_ALGORITHM: "${JWT_ALGORITHM:-HS256}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY:?Missing JWT_SECRET_KEY}"
      JWT_REFRESH_TOKEN_DURATION_DAYS: "${JWT_REFRESH_TOKEN_DURATION_DAYS:-7}"
      JWT_ACCESS_TOKEN_DURATION_MINUTES: "${JWT_ACCESS_TOKEN_DURATION_MINUTES:-15}"
      # imgpush
      IMGPUSH_HOST: "${IMGPUSH_HOST:-localhost}"
      IMGPUSH_PORT: "${IMGPUSH_PORT:-5000}"
      # email
      EMAIL_SERVER: "${EMAIL_SERVER:?Missing EMAIL_SERVER}"
      EMAIL_PORT: "${EMAIL_PORT:-465}"
      EMAIL_USERNAME: "${EMAIL_USERNAME:?Missing EMAIL_USERNAME}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD:?Missing EMAIL_PASSWORD}"
      EMAIL_FROM_EMAIL: "${EMAIL_FROM_EMAIL:?Missing EMAIL_FROM_EMAIL}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME:-Babytroc}"
    depends_on:
      - images
    ports:
      - 127.0.0.1:8080:8080
    network_mode: "host"
  # frontend server
  babytroc-gui:
    image: "ghcr.io/vianneyrousset/babytroc-gui:latest"
    container_name: "babytroc-gui"
    depends_on:
      - babytroc-api
    ports:
      - 127.0.0.1:3000:3000
