/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		AspectRatio: typeof import("radix-vue")["AspectRatio"];
		CheckboxIndicator: typeof import("radix-vue")["CheckboxIndicator"];
		CheckboxRoot: typeof import("radix-vue")["CheckboxRoot"];
		CollapsibleContent: typeof import("radix-vue")["CollapsibleContent"];
		CollapsibleRoot: typeof import("radix-vue")["CollapsibleRoot"];
		CollapsibleTrigger: typeof import("radix-vue")["CollapsibleTrigger"];
		DropdownMenuArrow: typeof import("radix-vue")["DropdownMenuArrow"];
		DropdownMenuCheckboxItem: typeof import(
			"radix-vue",
		)["DropdownMenuCheckboxItem"];
		DropdownMenuContent: typeof import("radix-vue")["DropdownMenuContent"];
		DropdownMenuItem: typeof import("radix-vue")["DropdownMenuItem"];
		DropdownMenuItemIndicator: typeof import(
			"radix-vue",
		)["DropdownMenuItemIndicator"];
		DropdownMenuLabel: typeof import("radix-vue")["DropdownMenuLabel"];
		DropdownMenuPortal: typeof import("radix-vue")["DropdownMenuPortal"];
		DropdownMenuRadioGroup: typeof import(
			"radix-vue",
		)["DropdownMenuRadioGroup"];
		DropdownMenuRadioItem: typeof import("radix-vue")["DropdownMenuRadioItem"];
		DropdownMenuRoot: typeof import("radix-vue")["DropdownMenuRoot"];
		DropdownMenuSeparator: typeof import("radix-vue")["DropdownMenuSeparator"];
		DropdownMenuSub: typeof import("radix-vue")["DropdownMenuSub"];
		DropdownMenuSubContent: typeof import(
			"radix-vue",
		)["DropdownMenuSubContent"];
		DropdownMenuSubTrigger: typeof import(
			"radix-vue",
		)["DropdownMenuSubTrigger"];
		DropdownMenuTrigger: typeof import("radix-vue")["DropdownMenuTrigger"];
		NumberFieldDecrement: typeof import("radix-vue")["NumberFieldDecrement"];
		NumberFieldIncrement: typeof import("radix-vue")["NumberFieldIncrement"];
		NumberFieldInput: typeof import("radix-vue")["NumberFieldInput"];
		NumberFieldRoot: typeof import("radix-vue")["NumberFieldRoot"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SliderRange: typeof import("radix-vue")["SliderRange"];
		SliderRoot: typeof import("radix-vue")["SliderRoot"];
		SliderThumb: typeof import("radix-vue")["SliderThumb"];
		SliderTrack: typeof import("radix-vue")["SliderTrack"];
		Toggle: typeof import("radix-vue")["Toggle"];
	}
}
