/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    NumberFieldDecrement: typeof import('radix-vue')['NumberFieldDecrement']
    NumberFieldIncrement: typeof import('radix-vue')['NumberFieldIncrement']
    NumberFieldInput: typeof import('radix-vue')['NumberFieldInput']
    NumberFieldRoot: typeof import('radix-vue')['NumberFieldRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderRange: typeof import('radix-vue')['SliderRange']
    SliderRoot: typeof import('radix-vue')['SliderRoot']
    SliderThumb: typeof import('radix-vue')['SliderThumb']
    SliderTrack: typeof import('radix-vue')['SliderTrack']
    Toggle: typeof import('radix-vue')['Toggle']
  }
}
