/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AspectRatio: typeof import('radix-vue')['AspectRatio']
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderRange: typeof import('radix-vue')['SliderRange']
    SliderRoot: typeof import('radix-vue')['SliderRoot']
    SliderThumb: typeof import('radix-vue')['SliderThumb']
    SliderTrack: typeof import('radix-vue')['SliderTrack']
    Toggle: typeof import('radix-vue')['Toggle']
  }
}
