import os

# POSTGRES_USER = os.environ["POSTGRES_USER"]
# POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
# POSTGRES_PORT = os.environ["POSTGRES_PORT"]
# DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db:{POSTGRES_PORT}/kindbaby"

USER_NAME_MIN_LENGTH = 3
USER_NAME_MAX_LENGTH = 30

ITEM_NAME_MIN_LENGTH = 5
ITEM_NAME_MAX_LENGTH = 30
ITEM_DESCRIPTION_MIN_LENGTH = 20
ITEM_DESCRIPTION_MAX_LENGTH = 600

AVATAR_SEED_MIN_LENGTH = 10
AVATAR_SEED_MAX_LENGTH = 64
