import os

POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]
DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@db:{POSTGRES_PORT}/kindbaby"

ITEM_NAME_MIN_LENGTH = 5
ITEM_NAME_MAX_LENGTH = 30
ITEM_DESCRIPTION_MIN_LENGTH = 50
ITEM_DESCRIPTION_MAX_LENGTH = 600
