[env]
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_DATABASE = "babytroc"
POSTGRES_USER = "babytroc"
IMGPUSH_HOST = "localhost"
IMGPUSH_PORT = 5000
_.file = ".env.yaml"
_.python.venv = { path = ".venv", create = true }

[tools]
python = { version = "3.13", virtualenv = ".venv" }
ruff = "latest"
uv = "latest"

[tasks."deps:mypy"]
description = "Install mypy linter"
run = "uv pip install mypy"

[tasks.deps]
description = "Install dependencies"
run = "uv sync"

[tasks.deps-dev]
description = "Install dev dependencies"
run = "uv sync --group dev"

[tasks.dev]
description = "Run the application"
depends = ["deps"]
run = "./entrypoint.sh"

[tasks.prepare]
description = "Prepare database"
run = "alembic upgrade head"

[tasks."lint:ruff"]
description = "Lint - ruff pass"
depends = ["deps", "deps-dev"]
run = "ruff check ."

[tasks."lint:mypy"]
description = "Lint - mypy pass"
depends = ["deps", "deps-dev"]
run = "mypy stubs app seed tests"

[tasks.lint]
description = "Lint the code"
depends = ["lint:*"]

[tasks.test]
description = "Test the code"
depends = ["deps", "deps-dev"]
run = "pytest"

[tasks.build]
description = "Build docker image"
run = "docker build . --tag=vianneyrousset/babytroc-api"
