[env]
_.file = ".env.yaml"
_.python.venv = { path = ".venv", create = true }

[tools]
python = { version = "3.13", virtualenv = ".venv" }
ruff = "latest"
uv = "latest"

[tasks."deps:mypy"]
description = "Install mypy linter"
run = "uv pip install mypy"

[tasks.deps]
description = "Install dependencies"
run = "uv sync"

[tasks.deps-dev]
description = "Install dev dependencies"
run = "uv sync --group dev"

[tasks.dev]
description = "Run the application"
depends = ["deps", "deps-dev", "prepare"]
run = "uv run babycli server start"

[tasks.prepare]
description = "Prepare database"
depends = ["deps"]
run = "alembic upgrade head"

[tasks."lint:ruff"]
description = "Lint - ruff pass"
depends = ["deps", "deps-dev"]
run = "ruff check ."

[tasks."lint:mypy"]
description = "Lint - mypy pass"
depends = ["deps", "deps-dev"]
run = "mypy stubs src tests"

[tasks.lint]
description = "Lint the code"
depends = ["lint:*"]

[tasks.test]
description = "Test the code"
depends = ["deps", "deps-dev", "check-test"]
run = "pytest"

[tasks.check]
description = "Run health checks on external services"
depends = ["deps"]
run = "babycli check"

[tasks.check-test]
description = "Run health checks on external services for testing"
depends = ["deps"]
run = "babycli check --test"

[tasks.build]
description = "Build docker image"
run = "docker build . --tag=vianneyrousset/babytroc-api"

[tasks.clear-mypy-cache]
description = "Clear mypy cache"
run = "rm -rf `find -iname '.mypy_cache'`"

[tasks.babycli]
description = "Run babycli operations CLI"
depends = ["deps", "deps-dev"]
run = "uv run babycli"
