[tool.ruff]
select = ["E", "F", "W"]
extend-select = [
  "ASYNC",
  "B",
  "C",
  "E",
  "ERA",
  "EM",
  "F",
  "G",
  "I",
  "N",
  "PT",
  "PTH",
  "RUF",
  "S",
  "TCH",
  "TID",
  "UP",
]
[tool.ruff.per-file-ignores]
"tests/test_*.py" = ["S101"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = "."
