[tool.ruff]
select = ["E", "F", "W"]
extend-select = [
  "ASYNC",
  "B",
  "C",
  "E",
  "ERA",
  "EM",
  "F",
  "G",
  "I",
  "N",
  "PT",
  "PTH",
  "RUF",
  "S",
  "TCH",
  "TID",
  "UP",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "class"
pythonpath = "."
