name: Linting
run-name: Linting check for commit "${{ github.event.head_commit.message }}" in "${{ github.ref_name }}"

on:

  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["dev", "rc", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:

  api-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run lint
        working-directory: ./api

  gui-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run lint
        working-directory: ./gui
