name: Publish

on:
  workflow_run:
    workflows: [Linting, Tests]
    branches: [main]
    types:
      - completed

jobs:

  publish-github-container-api:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: './api'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: VianneyRousset/babytroc-api:latest

  publish-github-container-gui:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: './gui'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: VianneyRousset/babytroc-gui:latest
