name: Publish
run-name: Publishing "${{ github.ref_name }}"

on:
  workflow_run:
    workflows: [Tests]
    branches: [main]
    types:
      - completed

jobs:

  publish-github-container-api:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    defaults:
        run:
          working-directory: './api'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:api"
          push: true
          tags: ghcr.io/vianneyrousset/babytroc-api:latest

  publish-github-container-gui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
        run:
          working-directory: './gui'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:gui"
          push: true
          tags: ghcr.io/vianneyrousset/babytroc-gui:latest
