name: Tests
run-name: Testing commit "${{ github.event.head_commit.message }}" in "${{ github.ref_name }}"
on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["dev", "rc", "main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  MISE_EXPERIMENTAL: true
jobs:
  api-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: babytroc
          POSTGRES_PASSWORD: xxx
        ports:
          - 5432:5432
      imgpush:
        image: hauxir/imgpush
        env:
          MAX_UPLOADS_PER_MINUTE: 100
          MAX_UPLOADS_PER_HOUR: 1000
          MAX_UPLOADS_PER_DAY: 10000
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run test
        working-directory: ./api
        env:
          HOST_NAME: test
          APP_NAME: test
          POSTGRES_PASSWORD: xxx
          JWT_ALGORITHM: "HS256"
          JWT_SECRET_KEY: "1234"
          JWT_REFRESH_TOKEN_DURATION_DAYS: "7"
          JWT_ACCESS_TOKEN_DURATION_MINUTES: "15"
          ACCOUNT_PASSWORD_RESET_AUTHORIZATION_DURATION_MINUTES: "20"
          EMAIL_SERVER: "fake.server.test"
          EMAIL_PORT: "465"
          EMAIL_USERNAME: "test"
          EMAIL_PASSWORD: "test"
          EMAIL_FROM_EMAIL: "pqhyhijbblvtncgj@cbnfukghppneopdz.com"
          EMAIL_FROM_NAME: "test"
